// Enhanced mock data with more features
export const mockTurfs = [
  {
    id: 1,
    name: "Elite Sports Arena",
    address: "123 Sports Complex, Downtown",
    distance: 2.5,
    price: 1200,
    rating: 4.8,
    reviews: 156,
    images: [
      "/placeholder.svg?height=300&width=400&text=Elite+Arena+Main",
      "/placeholder.svg?height=300&width=400&text=Elite+Arena+Night",
      "/placeholder.svg?height=300&width=400&text=Elite+Arena+Facilities",
      "/placeholder.svg?height=300&width=400&text=Elite+Arena+Changing+Room",
    ],
    videoTour: "/placeholder.svg?height=200&width=300&text=Video+Tour",
    amenities: ["Parking", "WiFi", "Changing Room", "Floodlights", "CCTV", "First Aid", "Cafeteria", "AC Lounge"],
    coordinates: { lat: 28.6139, lng: 77.209 },
    phone: "+91 9876543210",
    email: "elite@sports.com",
    website: "https://elitesports.com",
    description: "Premium artificial turf with professional lighting and world-class facilities.",
    detailedDescription:
      "Our state-of-the-art facility features FIFA-approved artificial turf, professional floodlighting system, and comprehensive amenities.",
    openingHours: "05:00 AM - 11:00 PM",
    capacity: 22,
    surface: "Artificial Grass",
    size: "100x60 meters",
    established: "2018",
    owner: "Elite Sports Pvt Ltd",
    socialMedia: {
      facebook: "https://facebook.com/elitesports",
      instagram: "https://instagram.com/elitesports",
      twitter: "https://twitter.com/elitesports",
    },
    weatherDependent: false,
    loyaltyPoints: 120,
    groupDiscounts: [
      { minPeople: 10, discount: 10 },
      { minPeople: 20, discount: 15 },
      { minPeople: 30, discount: 20 },
    ],
    equipment: [
      { name: "Football", price: 50, available: 10 },
      { name: "Bibs", price: 20, available: 30 },
      { name: "Cones", price: 30, available: 20 },
      { name: "Goals", price: 100, available: 4 },
    ],
    tournaments: [
      { name: "Weekend League", date: "2024-02-15", prize: "₹50,000", participants: 16 },
      { name: "Corporate Cup", date: "2024-03-01", prize: "₹1,00,000", participants: 32 },
    ],
    weather: {
      temperature: 28,
      condition: "sunny",
      humidity: 65,
      windSpeed: 12,
    },
    timeSlots: [
      { time: "06:00-07:00", available: true, price: 1000, demand: "low" },
      { time: "07:00-08:00", available: false, price: 1200, demand: "high" },
      { time: "08:00-09:00", available: true, price: 1200, demand: "medium" },
      { time: "09:00-10:00", available: true, price: 1000, demand: "low" },
      { time: "17:00-18:00", available: true, price: 1500, demand: "high" },
      { time: "18:00-19:00", available: false, price: 1500, demand: "high" },
      { time: "19:00-20:00", available: true, price: 1800, demand: "very-high" },
      { time: "20:00-21:00", available: true, price: 1800, demand: "very-high" },
    ],
    reviewsList: [
      {
        id: 1,
        user: "Rahul Sharma",
        rating: 5,
        comment: "Excellent facility with great maintenance. Highly recommended!",
        date: "2024-01-10",
        helpful: 12,
      },
      {
        id: 2,
        user: "Priya Patel",
        rating: 4,
        comment: "Good turf but parking can be challenging during peak hours.",
        date: "2024-01-08",
        helpful: 8,
      },
    ],
  },
  {
    id: 2,
    name: "Green Field Sports",
    address: "456 Park Avenue, Central",
    distance: 4.2,
    price: 800,
    rating: 4.5,
    reviews: 89,
    images: [
      "/placeholder.svg?height=300&width=400&text=Green+Field+Main",
      "/placeholder.svg?height=300&width=400&text=Green+Field+Grass",
      "/placeholder.svg?height=300&width=400&text=Green+Field+Parking",
    ],
    videoTour: "/placeholder.svg?height=200&width=300&text=Green+Field+Tour",
    amenities: ["Parking", "Cafeteria", "First Aid", "Natural Grass", "Sprinkler System"],
    coordinates: { lat: 28.6289, lng: 77.2065 },
    phone: "+91 9876543211",
    email: "green@field.com",
    website: "https://greenfield.com",
    description: "Natural grass field with excellent drainage system and eco-friendly facilities.",
    detailedDescription:
      "Experience football on natural grass with our advanced drainage system ensuring playability in all weather conditions.",
    openingHours: "06:00 AM - 10:00 PM",
    capacity: 22,
    surface: "Natural Grass",
    size: "105x68 meters",
    established: "2015",
    owner: "Green Sports Foundation",
    socialMedia: {
      facebook: "https://facebook.com/greenfield",
      instagram: "https://instagram.com/greenfield",
    },
    weatherDependent: true,
    loyaltyPoints: 80,
    groupDiscounts: [
      { minPeople: 15, discount: 12 },
      { minPeople: 25, discount: 18 },
    ],
    equipment: [
      { name: "Football", price: 40, available: 8 },
      { name: "Bibs", price: 15, available: 25 },
    ],
    tournaments: [{ name: "Green Cup", date: "2024-02-20", prize: "₹25,000", participants: 12 }],
    weather: {
      temperature: 26,
      condition: "cloudy",
      humidity: 70,
      windSpeed: 8,
    },
    timeSlots: [
      { time: "06:00-07:00", available: true, price: 600, demand: "low" },
      { time: "07:00-08:00", available: true, price: 800, demand: "medium" },
      { time: "08:00-09:00", available: false, price: 800, demand: "medium" },
      { time: "09:00-10:00", available: true, price: 700, demand: "low" },
      { time: "17:00-18:00", available: true, price: 1000, demand: "high" },
      { time: "18:00-19:00", available: true, price: 1000, demand: "high" },
      { time: "19:00-20:00", available: false, price: 1200, demand: "very-high" },
      { time: "20:00-21:00", available: true, price: 1200, demand: "high" },
    ],
    reviewsList: [
      {
        id: 3,
        user: "Amit Kumar",
        rating: 5,
        comment: "Love playing on natural grass! Great experience.",
        date: "2024-01-12",
        helpful: 15,
      },
    ],
  },
  {
    id: 3,
    name: "Champions Ground",
    address: "789 Victory Road, North",
    distance: 7.8,
    price: 1500,
    rating: 4.9,
    reviews: 234,
    images: [
      "/placeholder.svg?height=300&width=400&text=Champions+Main",
      "/placeholder.svg?height=300&width=400&text=Champions+VIP",
      "/placeholder.svg?height=300&width=400&text=Champions+Trophy+Room",
      "/placeholder.svg?height=300&width=400&text=Champions+Restaurant",
    ],
    videoTour: "/placeholder.svg?height=200&width=300&text=Champions+Tour",
    amenities: [
      "Parking",
      "WiFi",
      "Changing Room",
      "Floodlights",
      "Cafeteria",
      "AC Lounge",
      "VIP Box",
      "Pro Shop",
      "Physiotherapy",
      "Live Streaming",
    ],
    coordinates: { lat: 28.6448, lng: 77.2167 },
    phone: "+91 9876543212",
    email: "champions@ground.com",
    website: "https://championsground.com",
    description: "State-of-the-art facility with premium amenities and professional setup for elite players.",
    detailedDescription:
      "The ultimate destination for serious football enthusiasts. Features include professional-grade facilities, VIP viewing areas, live streaming capabilities, and on-site physiotherapy services.",
    openingHours: "05:00 AM - 12:00 AM",
    capacity: 22,
    surface: "Hybrid Grass",
    size: "105x68 meters",
    established: "2020",
    owner: "Champions Sports International",
    socialMedia: {
      facebook: "https://facebook.com/championsground",
      instagram: "https://instagram.com/championsground",
      twitter: "https://twitter.com/championsground",
      youtube: "https://youtube.com/championsground",
    },
    weatherDependent: false,
    loyaltyPoints: 150,
    groupDiscounts: [
      { minPeople: 8, discount: 8 },
      { minPeople: 16, discount: 15 },
      { minPeople: 24, discount: 22 },
    ],
    equipment: [
      { name: "Professional Football", price: 80, available: 15 },
      { name: "Training Bibs", price: 25, available: 40 },
      { name: "Agility Cones", price: 40, available: 30 },
      { name: "Professional Goals", price: 150, available: 6 },
      { name: "Speed Ladder", price: 60, available: 8 },
    ],
    tournaments: [
      { name: "Champions League", date: "2024-02-25", prize: "₹2,00,000", participants: 64 },
      { name: "Elite Cup", date: "2024-03-15", prize: "₹1,50,000", participants: 32 },
    ],
    weather: {
      temperature: 30,
      condition: "sunny",
      humidity: 60,
      windSpeed: 15,
    },
    timeSlots: [
      { time: "06:00-07:00", available: true, price: 1200, demand: "medium" },
      { time: "07:00-08:00", available: true, price: 1500, demand: "high" },
      { time: "08:00-09:00", available: true, price: 1500, demand: "high" },
      { time: "09:00-10:00", available: false, price: 1300, demand: "medium" },
      { time: "17:00-18:00", available: true, price: 1800, demand: "very-high" },
      { time: "18:00-19:00", available: true, price: 1800, demand: "very-high" },
      { time: "19:00-20:00", available: true, price: 2000, demand: "very-high" },
      { time: "20:00-21:00", available: false, price: 2000, demand: "very-high" },
    ],
    reviewsList: [
      {
        id: 4,
        user: "Vikram Singh",
        rating: 5,
        comment: "World-class facility! Worth every penny. The VIP experience is amazing.",
        date: "2024-01-15",
        helpful: 25,
      },
      {
        id: 5,
        user: "Sneha Reddy",
        rating: 5,
        comment: "Professional setup with excellent staff. Highly recommended for tournaments.",
        date: "2024-01-13",
        helpful: 18,
      },
    ],
  },
]
